name: Build and Push Docker Image

on:
  push:
    branches: [main] # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Specify the Node.js version

      - name: Install dependencies and build
        run: |
          cd dashboard
          npm ci
          npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: szeminator/fhtiming:latest
